---
all:
  vars:
    upgrade_paths:
      pr_419: &pr_419
        - from: "4.16"
          channel: stable-4.17
          version: 4.17.35
          #admin_acks:
          # No admin-acks identified at https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/updating_clusters/preparing-to-update-a-cluster#kube-api-removals_updating-cluster-prepare
        - from: "4.17"
          channel: stable-4.18   # https://access.redhat.com/support/policy/updates/openshift#dates  4.18 GA on 2025-02-25.  Use fast-4.18 until update available in stable-4.18 (estimated GA + 45-90d per https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/updating_clusters/understanding-openshift-updates-1#update-availability_understanding-openshift-updates)
          version: 4.18.20
          #admin_acks:
          # No admin-acks identified at https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/updating_clusters/preparing-to-update-a-cluster#kube-api-removals_updating-cluster-prepare
        - from: "4.18"
          image: "registry.build10.ci.openshift.org/ci-ln-fqnfqib/release:latest"
          force: true
          allow-explicit-upgrade: true
          admin_acks:
            - '{"data":{"ack-4.18-kube-1.32-api-removals-in-4.19":"true"}}'


standard_clusters:
  # "standard" in the sense that the unspecialized standard_cluster role will work
  # See byok_cluster for an example that is not "standard"
  hosts:
    ci-419:
      upgrade: *pr_419
      version: 4.16.30
  vars:
    name: aro
    resource_group: "{{ CLUSTERPREFIX }}-{{ inventory_hostname }}-{{ location }}"
    network_prefix_cidr: 10.0.0.0/22
    master_cidr: 10.0.0.0/23
    master_vm_size: Standard_D8s_v3
    worker_cidr: 10.0.2.0/23
    worker_vm_size: Standard_D4s_v3
