# Copy the pull secret to the delegate host if needed
- name: prepare_pullsecret | Copy pull secret to delegate
  when: pull_secret_should_copy
  delegate_to: "{{ delegation }}"
  ansible.builtin.copy:
    src: "{{ pull_secret_file }}"       # local file path on the Ansible control node, i.e. localhost (e.g., /tmp/pull-secret.txt)
    dest: "{{ pull_secret_file }}"      # to the same path on the remote jumphost delegate
    mode: '0644'

# Set up azcli argument inclusion for Day-0
- name: prepare_pullsecret | Confirm pull secret will be used via azcli
  when: pull_secret_should_azcli
  ansible.builtin.debug:
    msg: "Pull secret will be passed to 'az aro create' via --pull-secret argument."
    verbosity: 1
  delegate_to: localhost

- name: prepare_pullsecret | Debugging pull secret file existence
  ansible.builtin.debug:
    msg: "Pull secret file exists: {{ pull_secret_file_stat_exists | default(false) }}"
    verbosity: 2
  delegate_to: localhost

- name: prepare_pullsecret | Debugging delegated task execution on remote
  ansible.builtin.debug:
    msg: "Executing on delegate: {{ delegation }} with pull secret file: {{ pull_secret_file }}"
    verbosity: 2
  delegate_to: "{{ delegation }}"

# Set up Kubernetes secret for Day-2
- name: prepare_pullsecret | Create Kubernetes secret from pull secret file
  when: pull_secret_should_k8s
  delegate_to: "{{ delegation }}"
  block:
    - name: prepare_pullsecret | Read and encode pull secret
      set_fact:
        pull_secret_data: "{{ lookup('file', pull_secret_file) | b64encode }}"

    - name: prepare_pullsecret | Apply Kubernetes Secret to openshift-config
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: pull-secret
            namespace: openshift-config
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ pull_secret_data }}"
